name = "Kibe Utilities"
filename = "kibe-1.8.1-BETA+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3424/890/kibe-1.8.1-BETA+1.17.jar"
hash-format = "murmur2"
hash = "1724210355"

[update]
[update.curseforge]
file-id = 3424890
project-id = 388832
release-channel = "beta"
